In [2]:
import pandas as pd
import requests

In [3]:
endpoint = 'https://data.cdc.gov/resource/x9gk-5huc.json'

In [4]:
response=requests.get(endpoint)

In [5]:
data=response.text

In [6]:
df= pd.read_json(data)

In [8]:
camp_df=df.loc[df['label']=='Campylobacteriosis']

In [12]:
df.label.unique()

array(['Anthrax', 'Arboviral diseases, Chikungunya virus disease',
       'Arboviral diseases, Eastern equine encephalitis virus disease',
       'Arboviral diseases, Jamestown Canyon  virus disease',
       'Arboviral diseases, La Crosse  virus disease',
       'Arboviral diseases, Powassan virus disease',
       'Arboviral diseases, St. Louis encephalitis virus disease',
       'Arboviral diseases, West Nile virus disease',
       'Arboviral diseases, Western equine encephalitis virus disease',
       'Babesiosis', 'Botulism, Foodborne', 'Botulism, Infant',
       'Botulism, Other (wound & unspecified)', 'Brucellosis',
       'Campylobacteriosis'], dtype=object)

In [13]:
endpoint2 = 'https://data.cdc.gov/resource/kxvg-q6s7.json'

In [14]:
response1= requests.get(endpoint2)

In [15]:
data2=response1.text

In [16]:
df2=pd.read_json(data2)

In [29]:
df2.loc[df2['mumps_current_week_flag'].isna()==False]

,reporting_area,mmwr_year,mmwr_week,mumps_current_week_flag,mumps_previous_52_weeks_max,mumps_cum_2022_flag,mumps_cum_2021,novel_influenza_a_virus_1,novel_influenza_a_virus_2,novel_influenza_a_virus_5,novel_influenza_a_virus_7,location_2,reporting_area_sort,mumps_cum_2021_flag,location_1,tableoney,:@computed_region_skr5_azej,:@computed_region_hjsp_umg2,mumps_current_week,mumps_cum_2022
0,US RESIDENTS,2022,1,-,8,-,1.0,-,0,-,-,US RESIDENTS,202200101,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NEW ENGLAND,2022,1,-,1,-,NaN,-,0,-,-,NEW ENGLAND,202200102,-,NaN,NaN,NaN,NaN,NaN,NaN
2,CONNECTICUT,2022,1,-,1,-,NaN,-,0,-,-,NaN,202200103,-,CONNECTICUT,"{'type': 'Point', 'coordinates': [-72.738288, ...",1043.0,24.0,NaN,NaN
3,MAINE,2022,1,-,1,-,NaN,-,0,-,-,NaN,202200104,-,MAINE,"{'type': 'Point', 'coordinates': [-69.06137, 4...",1725.0,49.0,NaN,NaN
4,MASSACHUSETTS,2022,1,-,1,-,NaN,-,0,-,-,NaN,202200105,-,MASSACHUSETTS,"{'type': 'Point', 'coordinates': [-71.481104, ...",1916.0,25.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,NORTHERN MARIANA ISLANDS,2022,5,-,0,-,NaN,-,0,-,-,NaN,202200565,-,NORTHERN MARIANA ISLANDS,"{'type': 'Point', 'coordinates': [145.725693, ...",NaN,NaN,NaN,NaN
415,GUAM,2022,5,-,0,-,NaN,-,0,-,-,NaN,202200566,-,GUAM,"{'type': 'Point', 'coordinates': [144.653198, ...",NaN,NaN,NaN,NaN
416,PUERTO RICO,2022,5,-,0,-,NaN,-,0,-,-,NaN,202200567,-,PUERTO RICO,"{'type': 'Point', 'coordinates': [-66.414655, ...",3087.0,NaN,NaN,NaN
417,U.S. VIRGIN ISLANDS,2022,5,-,0,-,NaN,-,0,-,-,NaN,202200568,-,U.S. VIRGIN ISLANDS,NaN,NaN,NaN,NaN,NaN
418,NON-US RESIDENTS,2022,5,-,0,-,NaN,-,0,-,-,NON-US RESIDENTS,202200569,-,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
endpoint3='https://data.cdc.gov/resource/fj6i-3v3k.json?$query=SELECT%20reporting_area%2C%20mmwr_year%2C%20mmwr_week%2C%20hepatitis_b_perinatal%2C%20hepatitis_b_perinatal_1%2C%20hepatitis_b_perinatal_2%2C%20hepatitis_b_perinatal_3%2C%20hepatitis_b_perinatal_4%2C%20hepatitis_b_perinatal_5%2C%20hepatitis_b_perinatal_6%2C%20hepatitis_b_perinatal_7%2C%20hepatitis_c_acute_confirmed%2C%20hepatitis_c_acute_confirmed_1%2C%20hepatitis_c_acute_confirmed_2%2C%20hepatitis_c_acute_previous%2C%20hepatitis_c_acute_confirmed_3%2C%20hepatitis_c_acute_confirmed_4%2C%20hepatitis_c_acute_confirmed_5%2C%20hepatitis_c_acute_confirmed_6%2C%20hepatitis_c_acute_probable%2C%20hepatitis_c_acute_probable_1%2C%20hepatitis_c_acute_probable_2%2C%20hepatitis_c_acute_probable_3%2C%20hepatitis_c_acute_probable_4%2C%20hepatitis_c_acute_probable_5%2C%20hepatitis_c_acute_probable_6%2C%20hepatitis_c_acute_probable_7%2C%20location_1%2C%20location_2%2C%20reporting_area_sort%2C%20tableoneq%20ORDER%20BY%20reporting_area_sort%20ASC'

In [28]:
response2=requests.get(endpoint3)

In [31]:
data3=response2.text

In [34]:
hep_df3=pd.read_json(data3)

In [35]:
hep_df3

,reporting_area,mmwr_year,mmwr_week,hepatitis_b_perinatal_1,hepatitis_b_perinatal_2,hepatitis_b_perinatal_5,hepatitis_b_perinatal_7,hepatitis_c_acute_confirmed,hepatitis_c_acute_confirmed_2,hepatitis_c_acute_confirmed_3,...,hepatitis_c_acute_probable_1,hepatitis_c_acute_probable_5,hepatitis_c_acute_confirmed_6,hepatitis_c_acute_probable_7,location_1,tableoneq,hepatitis_b_perinatal_3,hepatitis_c_acute_previous,hepatitis_c_acute_probable_3,hepatitis_b_perinatal_6
0,US RESIDENTS,2022,1,-,4.0,-,-,5.0,274.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NEW ENGLAND,2022,1,-,1.0,-,-,NaN,10.0,NaN,...,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CONNECTICUT,2022,1,-,0.0,-,-,NaN,2.0,NaN,...,-,-,-,-,CONNECTICUT,"{'type': 'Point', 'coordinates': [-72.738288, ...",NaN,NaN,NaN,NaN
3,MAINE,2022,1,-,1.0,-,-,NaN,6.0,NaN,...,-,-,NaN,-,MAINE,"{'type': 'Point', 'coordinates': [-69.06137, 4...",NaN,NaN,NaN,NaN
4,MASSACHUSETTS,2022,1,-,1.0,-,-,NaN,6.0,NaN,...,-,-,NaN,NaN,MASSACHUSETTS,"{'type': 'Point', 'coordinates': [-71.481104, ...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,GUAM,2022,5,-,0.0,-,-,NaN,0.0,NaN,...,-,-,-,-,GUAM,"{'type': 'Point', 'coordinates': [144.653198, ...",NaN,NaN,NaN,NaN
416,PUERTO RICO,2022,5,-,0.0,-,-,NaN,NaN,NaN,...,N,N,N,N,PUERTO RICO,"{'type': 'Point', 'coordinates': [-66.414655, ...",NaN,NC,NC,NaN
417,U.S. VIRGIN ISLANDS,2022,5,-,0.0,-,-,NaN,0.0,NaN,...,-,-,-,-,U.S. VIRGIN ISLANDS,NaN,NaN,NaN,NaN,NaN
418,NON-US RESIDENTS,2022,5,-,0.0,-,-,NaN,0.0,NaN,...,-,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN
419,TOTAL,2022,5,-,4.0,-,NaN,5.0,274.0,123.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [36]:
endpoint4='https://data.cdc.gov/resource/vq7a-fvin.json?$query=SELECT%20reporting_area%2C%20mmwr_year%2C%20mmwr_week%2C%20vibriosis_any_species_of%2C%20vibriosis_any_species_of_1%2C%20vibriosis_any_species_of_2%2C%20vibriosis_any_species_of_3%2C%20vibriosis_any_species_of_4%2C%20vibriosis_any_species_of_5%2C%20vibriosis_any_species_of_6%2C%20vibriosis_any_species_of_7%2C%20vibriosis_any_species_of_8%2C%20vibriosis_any_species_of_9%2C%20vibriosis_any_species_of_10%2C%20vibriosis_any_species_of_11%2C%20vibriosis_any_species_of_12%2C%20vibriosis_any_species_of_13%2C%20vibriosis_any_species_of_14%2C%20vibriosis_any_species_of_15%2C%20location_1%2C%20location_2%2C%20reporting_area_sort%2C%20tableonell%20ORDER%20BY%20reporting_area_sort%20ASC'

In [37]:
response4=requests.get(endpoint4)

In [38]:
data_vib=response4.text

In [39]:
df_vib=pd.read_json(data_vib)

In [40]:
df_vib

,reporting_area,mmwr_year,mmwr_week,vibriosis_any_species_of_1,vibriosis_any_species_of_2,vibriosis_any_species_of_5,vibriosis_any_species_of_6,vibriosis_any_species_of_8,vibriosis_any_species_of_10,vibriosis_any_species_of_12,...,vibriosis_any_species_of_9,vibriosis_any_species_of_13,vibriosis_any_species_of_15,location_1,tableonell,vibriosis_any_species_of_7,vibriosis_any_species_of_3,vibriosis_any_species_of_11,vibriosis_any_species_of,vibriosis_any_species_of_4
0,US RESIDENTS,2021,1,-,53.0,-,8.0,2.0,20.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NEW ENGLAND,2021,1,-,10.0,-,1.0,NaN,5.0,NaN,...,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CONNECTICUT,2021,1,-,6.0,-,1.0,NaN,2.0,NaN,...,-,-,-,CONNECTICUT,"{'type': 'Point', 'coordinates': [-72.738288, ...",NaN,NaN,NaN,NaN,NaN
3,MAINE,2021,1,-,2.0,-,NaN,NaN,2.0,NaN,...,-,-,-,MAINE,"{'type': 'Point', 'coordinates': [-69.06137, 4...",-,NaN,NaN,NaN,NaN
4,MASSACHUSETTS,2021,1,-,6.0,-,NaN,NaN,2.0,NaN,...,-,-,-,MASSACHUSETTS,"{'type': 'Point', 'coordinates': [-71.481104, ...",-,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,INDIANA,2021,15,-,1.0,-,1.0,NaN,1.0,NaN,...,-,-,NaN,INDIANA,"{'type': 'Point', 'coordinates': [-86.2818, 39...",NaN,NaN,NaN,NaN,NaN
996,MICHIGAN,2021,15,-,2.0,-,3.0,NaN,1.0,NaN,...,-,-,NaN,MICHIGAN,"{'type': 'Point', 'coordinates': [-85.730977, ...",NaN,NaN,NaN,NaN,NaN
997,OHIO,2021,15,-,2.0,NaN,4.0,NaN,5.0,10.0,...,-,NaN,NaN,OHIO,"{'type': 'Point', 'coordinates': [-82.70936, 4...",NaN,NaN,NaN,NaN,5.0
998,WISCONSIN,2021,15,-,1.0,-,1.0,NaN,1.0,NaN,...,-,-,NaN,WISCONSIN,"{'type': 'Point', 'coordinates': [-89.732969, ...",NaN,NaN,NaN,NaN,NaN
999,WEST NORTH CENTRAL,2021,15,-,2.0,-,4.0,NaN,2.0,4.0,...,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
vax_endpoint='https://data.cdc.gov/resource/ee48-w5t6.json'

In [31]:
response_vax=requests.get(vax_endpoint)

In [32]:
data_vax=response_vax.text

In [33]:
df_vax=pd.read_json(data_vax)

In [34]:
df_vax

,vaccine,dose,geography_type,geography,year_season,dimension_type,dimension,coverage_estimate,_95_ci,population_sample_size
0,HPV,">=1 Dose, Females",HHS Regions/National,United States,2006,Age,13-17 Years,1.0,0.6 to 1.8,1335.0
1,HPV,">=1 Dose, Females",HHS Regions/National,United States,2007,Age,13-17 Years,25.1,22.3 to 28.1,1441.0
2,HPV,">=1 Dose, Females",HHS Regions/National,Region 1,2007,Age,13-17 Years,37.6,25.7 to 51.2,90.0
3,HPV,">=1 Dose, Females",HHS Regions/National,Region 2,2007,Age,13-17 Years,38.2,28.1 to 49.5,105.0
4,HPV,">=1 Dose, Females",HHS Regions/National,Region 3,2007,Age,13-17 Years,27.1,19.5 to 36.3,183.0
...,...,...,...,...,...,...,...,...,...,...
995,HPV,">=1 Dose, Females",States/Local Areas,Idaho,2021,Age,13-17 Years,81.8,73.0 to 88.2,153.0
996,HPV,">=1 Dose, Females",States/Local Areas,Illinois,2021,Age,13-17 Years,76.5,69.4 to 82.4,282.0
997,HPV,">=1 Dose, Females",States/Local Areas,IL-City of Chicago,2021,Age,13-17 Years,86.8,70.0 to 94.9,72.0
998,HPV,">=1 Dose, Females",States/Local Areas,IL-Rest of state,2021,Age,13-17 Years,74.2,66.0 to 81.0,210.0
999,HPV,">=1 Dose, Females",States/Local Areas,Indiana,2021,Age,13-17 Years,75.3,64.9 to 83.4,122.0

In [36]:
adult_vax=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/Adult_vax.csv')

In [82]:
adult_vax.loc[adult_vax.Geography=='Tennessee']

,Vaccine,Geography Type,Geography,FIPS,Survey Year,Dimension Type,Dimension,Estimate (%),95% CI (%),Sample Size
59,Pneumococcal,States/Local Areas,Tennessee,47,2008,18-64 Years at Increased Risk,"Black, Non-Hispanic",22.4,13.9 to 30.9,172.0
133,Pneumococcal,States/Local Areas,Tennessee,47,2009,18-64 Years at Increased Risk,"Black, Non-Hispanic",24.9,14.0 to 35.9,197.0
207,Pneumococcal,States/Local Areas,Tennessee,47,2010,18-64 Years at Increased Risk,"Black, Non-Hispanic",22.7,14.9 to 30.5,194.0
281,Pneumococcal,States/Local Areas,Tennessee,47,2011,18-64 Years at Increased Risk,"Black, Non-Hispanic",12.0,5.7 to 18.4,193.0
355,Pneumococcal,States/Local Areas,Tennessee,47,2012,18-64 Years at Increased Risk,"Black, Non-Hispanic",24.1,17.9 to 30.4,313.0
...,...,...,...,...,...,...,...,...,...,...
50478,Zoster (Shingles),States/Local Areas,Tennessee,47,2010,>=65 Years,Overall,13.0,10.2 to 15.7,935.0
50553,Zoster (Shingles),States/Local Areas,Tennessee,47,2014,>=65 Years,Overall,32.4,29.6 to 35.1,1858.0
50639,Zoster (Shingles),States/Local Areas,Tennessee,47,2017,>=65 Years,Overall,38.5,35.4 to 41.6,1617.0
50655,Zoster (Shingles),States/Local Areas,Tennessee,47,2018,>=65 Years,Overall,37.5,34.1 to 40.9,1384.0
50724,Zoster (Shingles),States/Local Areas,Tennessee,47,2020,>=65 Years,Overall,42.1,38.5 to 45.8,1289.0

In [39]:
ado_vax=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/Adolescent_Vax-13-17.csv')

In [41]:
ado_vax['Vaccine/Sample'].unique()

array(['HPV', 'Meningococcal Conjugate', 'Td or Tdap', 'Tdap',
       'Varicella', 'Hep A', 'MMR', 'HepB'], dtype=object)

In [85]:
ado_vax.loc[(ado_vax['Survey Year']=='2021')&(ado_vax['Geography']=='Tennessee')]

,Vaccine/Sample,Dose,Geography Type,Geography,Survey Year,Dimension Type,Dimension,Estimate (%),95% CI (%),Sample Size
1042,HPV,">=1 Dose, Females",States/Local Areas,Tennessee,2021,Age,13-17 Years,81.6,72.9 to 87.9,141.0
1907,HPV,">=1 Dose, Males",States/Local Areas,Tennessee,2021,Age,13-17 Years,69.3,59.8 to 77.4,174.0
3044,Meningococcal Conjugate,>=1 Dose,States/Local Areas,Tennessee,2021,Age,13-15 Years,87.4,80.6 to 92.1,188.0
4182,Meningococcal Conjugate,>=1 Dose,States/Local Areas,Tennessee,2021,Age,13-17 Years,88.1,82.9 to 91.9,315.0
6132,Td or Tdap,>=1 Dose,States/Local Areas,Tennessee,2021,Age,13-17 Years,94.0,89.8 to 96.5,315.0
7269,Tdap,>=1 Dose,States/Local Areas,Tennessee,2021,Age,13-15 Years,92.2,86.2 to 95.8,188.0
8408,Tdap,>=1 Dose,States/Local Areas,Tennessee,2021,Age,13-17 Years,92.0,87.3 to 95.0,315.0
10357,Varicella,>=1 Dose with no disease history,States/Local Areas,Tennessee,2021,Age,13-17 Years,96.2,92.6 to 98.1,287.0
10889,HPV,">=1 Dose, Males and Females",States/Local Areas,Tennessee,2021,Age,13-17 Years,75.3,68.9 to 80.8,315.0
11919,Hep A,>=2 Doses,States/Local Areas,Tennessee,2021,Age,13-17 Years,91.4,87.0 to 94.4,315.0
13942,MMR,>=2 Doses,States/Local Areas,Tennessee,2021,Age,13-17 Years,95.1,91.3 to 97.2,315.0
15082,Varicella,>=2 Doses or history of disease,States/Local Areas,Tennessee,2021,Age,13-17 Years,95.3,91.6 to 97.4,315.0
16201,Varicella,>=2 Doses with no disease history,States/Local Areas,Tennessee,2021,Age,13-15 Years,94.7,89.5 to 97.4,178.0
17321,Varicella,>=2 Doses with no disease history,States/Local Areas,Tennessee,2021,Age,13-17 Years,94.7,90.7 to 97.1,287.0
18461,HepB,>=3 Doses,States/Local Areas,Tennessee,2021,Age,13-17 Years,95.1,91.4 to 97.2,315.0
21506,Varicella,History of disease,States/Local Areas,Tennessee,2021,Age,13-17 Years,10.0,6.3 to 15.4,315.0
21865,HPV,"Up-to-Date, Females",States/Local Areas,Tennessee,2021,Age,13-15 Years,63.3,49.9 to 74.9,87.0
22397,HPV,"Up-to-Date, Females",States/Local Areas,Tennessee,2021,Age,13-17 Years,64.4,54.2 to 73.5,141.0
22775,HPV,"Up-to-Date, Males",States/Local Areas,Tennessee,2021,Age,13-15 Years,48.1,35.9 to 60.5,101.0
23307,HPV,"Up-to-Date, Males",States/Local Areas,Tennessee,2021,Age,13-17 Years,48.8,39.3 to 58.4,174.0
23606,HPV,"Up-to-Date, Males and Females",States/Local Areas,Tennessee,2021,Age,13-15 Years,55.8,46.6 to 64.7,188.0
24138,HPV,"Up-to-Date, Males and Females",States/Local Areas,Tennessee,2021,Age,13-17 Years,56.5,49.4 to 63.3,315.0

In [42]:
adult_vax.Vaccine.unique()

array(['Pneumococcal', 'Tdap', 'Td or Tdap', 'Zoster (Shingles)'],
      dtype=object)

In [44]:
pne_vax=adult_vax.loc[adult_vax.Vaccine=='Pneumococcal']

In [47]:
pne_vax21=pne_vax.loc[pne_vax['Survey Year']==2021]

In [83]:
pne_vax21.loc[pne_vax21['Geography']=='Tennessee']

,Vaccine,Geography Type,Geography,FIPS,Survey Year,Dimension Type,Dimension,Estimate (%),95% CI (%),Sample Size
1008,Pneumococcal,States/Local Areas,Tennessee,47,2021,18-64 Years at Increased Risk,"Black, Non-Hispanic",37.1,26.6 to 47.6,133.0
2027,Pneumococcal,States/Local Areas,Tennessee,47,2021,18-64 Years at Increased Risk,Hispanic,NaN,NaN,37.0
3046,Pneumococcal,States/Local Areas,Tennessee,47,2021,18-64 Years at Increased Risk,"Other or Multiple Races, Non-Hispanic",34.5,17.7 to 51.2,69.0
4065,Pneumococcal,States/Local Areas,Tennessee,47,2021,18-64 Years at Increased Risk,"White, Non-Hispanic",32.6,28.8 to 36.4,936.0
5084,Pneumococcal,States/Local Areas,Tennessee,47,2021,>=65 Years,"Black, Non-Hispanic",47.7,34.5 to 60.8,108.0
6103,Pneumococcal,States/Local Areas,Tennessee,47,2021,>=65 Years,Hispanic,NaN,NaN,7.0
7122,Pneumococcal,States/Local Areas,Tennessee,47,2021,>=65 Years,"Other or Multiple Races, Non-Hispanic",61.5,38.6 to 84.4,34.0
8141,Pneumococcal,States/Local Areas,Tennessee,47,2021,>=65 Years,"White, Non-Hispanic",73.2,69.8 to 76.6,1153.0
21267,Pneumococcal,States/Local Areas,Tennessee,47,2021,18-64 Years at Increased Risk,Overall,32.4,28.9 to 35.8,1190.0
34755,Pneumococcal,States/Local Areas,Tennessee,47,2021,>=65 Years,Overall,69.9,66.5 to 73.3,1327.0

In [54]:
pubschool=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/pubschool.csv')

C:\Users\Evan\AppData\Local\Temp\ipykernel_932\2297661209.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  pubschool=pd.read_csv('C:/Users/Evan/Desktop/NSS/Python/Capstone/NNDSSCapstone/Data/pubschool.csv')

In [55]:
pubschool

,X,Y,OBJECTID,NCESSCH,SURVYEAR,STABR,LEAID,ST_LEAID,LEA_NAME,SCH_NAME,...,HIALF,HI,TRALM,TRALF,TR,WHALM,WHALF,WH,LATCOD,LONCOD
0,-86.206200,34.260200,1,10000500870,2020-2021,AL,100005,AL-101,Albertville City,Albertville Middle School,...,230.0,469.0,19.0,10.0,29.0,187.0,184.0,371.0,34.260200,-86.206200
1,-86.204900,34.262200,2,10000500871,2020-2021,AL,100005,AL-101,Albertville City,Albertville High School,...,371.0,785.0,17.0,21.0,38.0,368.0,338.0,706.0,34.262200,-86.204900
2,-86.220100,34.273300,3,10000500879,2020-2021,AL,100005,AL-101,Albertville City,Albertville Intermediate School,...,253.0,481.0,17.0,12.0,29.0,177.0,168.0,345.0,34.273300,-86.220100
3,-86.221806,34.252700,4,10000500889,2020-2021,AL,100005,AL-101,Albertville City,Albertville Elementary School,...,237.0,497.0,7.0,8.0,15.0,180.0,160.0,340.0,34.252700,-86.221806
4,-86.193300,34.289800,5,10000501616,2020-2021,AL,100005,AL-101,Albertville City,Albertville Kindergarten and PreK,...,137.0,288.0,6.0,7.0,13.0,108.0,108.0,216.0,34.289800,-86.193300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100717,-64.917602,18.341950,100718,780003000024,2020-2021,VI,7800030,VI-001,Saint Thomas - Saint John School District,LOCKHART ELEMENTARY SCHOOL,...,29.0,59.0,1.0,1.0,2.0,2.0,4.0,6.0,18.341950,-64.917602
100718,-64.952483,18.338742,100719,780003000026,2020-2021,VI,7800030,VI-001,Saint Thomas - Saint John School District,ULLA F MULLER ELEMENTARY SCHOOL,...,34.0,64.0,2.0,1.0,3.0,4.0,5.0,9.0,18.338742,-64.952483
100719,-64.899024,18.354782,100720,780003000027,2020-2021,VI,7800030,VI-001,Saint Thomas - Saint John School District,YVONNE BOWSKY ELEMENTARY SCHOOL,...,25.0,57.0,NaN,NaN,NaN,6.0,3.0,9.0,18.354782,-64.899024
100720,-64.945940,18.336658,100721,780003000033,2020-2021,VI,7800030,VI-001,Saint Thomas - Saint John School District,CANCRYN JUNIOR HIGH SCHOOL,...,72.0,153.0,1.0,NaN,1.0,7.0,11.0,18.0,18.336658,-64.945940
100721,-64.890311,18.318230,100722,780003000034,2020-2021,VI,7800030,VI-001,Saint Thomas - Saint John School District,BERTHA BOSCHULTE JUNIOR HIGH,...,30.0,55.0,NaN,NaN,NaN,1.0,1.0,2.0,18.318230,-64.890311

In [98]:
pubschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False)

,X,Y,OBJECTID,NCESSCH,SURVYEAR,LEAID,ST_LEAID,LEA_NAME,SCH_NAME,LSTREET1,...,HIALF,HI,TRALM,TRALF,TR,WHALM,WHALF,WH,LATCOD,LONCOD
STABR,,,,,,,,,,,,,,,,,,,,,
CA,10330,10330,10330,10330,10330,10330,10330,10330,10330,10330,...,10116,10128,9356,9352,9699,9840,9812,9984,10330,10330
TX,9467,9467,9467,9467,9467,9467,9467,9467,9467,9467,...,8997,8997,8997,8997,8997,8997,8997,8997,9467,9467
NY,4831,4831,4831,4831,4831,4831,4831,4831,4831,4831,...,4710,4766,4135,4149,4435,4673,4624,4752,4831,4831
IL,4384,4384,4384,4384,4384,4384,4384,4384,4384,4384,...,3599,3722,3397,3357,3597,3626,3609,3685,4384,4384
FL,4267,4267,4267,4267,4267,4267,4267,4267,4267,4267,...,4213,4213,4213,4213,4213,4213,4213,4213,4267,4267
MI,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,...,3526,3526,3526,3526,3526,3526,3526,3526,3553,3553
OH,3532,3532,3532,3532,3532,3532,3532,3532,3532,3532,...,3531,3531,3531,3531,3531,3531,3531,3531,3532,3532
PA,2952,2952,2952,2952,2952,2952,2952,2952,2952,2952,...,2946,2946,2946,2946,2946,2946,2946,2946,2952,2952
NC,2730,2730,2730,2730,2730,2730,2730,2730,2730,2730,...,2679,2679,2679,2679,2679,2679,2679,2679,2730,2730
NJ,2566,2566,2566,2566,2566,2566,2566,2566,2566,2566,...,2527,2541,2140,2140,2262,2469,2452,2500,2566,2566
MN,2542,2542,2542,2542,2542,2542,2542,2542,2542,2542,...,2353,2444,2327,2282,2387,2471,2461,2489,2542,2542
WA,2507,2507,2507,2507,2507,2507,2507,2507,2507,2507,...,2465,2487,2382,2379,2433,2495,2490,2500,2507,2507
AZ,2480,2480,2480,2480,2480,2480,2480,2480,2480,2480,...,2350,2350,2350,2350,2350,2350,2350,2350,2480,2480
MO,2460,2460,2460,2460,2460,2460,2460,2460,2460,2460,...,2102,2242,2035,2040,2141,2410,2408,2420,2460,2460
GA,2311,2311,2311,2311,2311,2311,2311,2311,2311,2311,...,2307,2307,2307,2307,2307,2307,2307,2307,2311,2311
WI,2258,2258,2258,2258,2258,2258,2258,2258,2258,2258,...,2125,2198,2054,2073,2162,2206,2199,2215,2258,2258
VA,2130,2130,2130,2130,2130,2130,2130,2130,2130,2130,...,2118,2118,2118,2118,2118,2118,2118,2118,2130,2130
CO,1927,1927,1927,1927,1927,1927,1927,1927,1927,1927,...,1911,1913,1733,1734,1815,1913,1911,1917,1927,1927
IN,1902,1902,1902,1902,1902,1902,1902,1902,1902,1902,...,1843,1885,1850,1841,1880,1894,1885,1899,1902,1902
TN,1880,1880,1880,1880,1880,1880,1880,1880,1880,1880,...,1796,1843,1718,1708,1785,1837,1813,1856,1880,1880
MA,1845,1845,1845,1845,1845,1845,1845,1845,1845,1845,...,1810,1829,1750,1723,1797,1832,1827,1837,1845,1845
OK,1790,1790,1790,1790,1790,1790,1790,1790,1790,1790,...,1698,1753,1789,1787,1789,1783,1779,1783,1790,1790
AL,1559,1559,1559,1559,1559,1559,1559,1559,1559,1559,...,1347,1347,1347,1347,1347,1347,1347,1347,1559,1559
KY,1532,1532,1532,1532,1532,1532,1532,1532,1532,1532,...,1465,1500,1445,1444,1486,1524,1523,1529,1532,1532
MD,1421,1421,1421,1421,1421,1421,1421,1421,1421,1421,...,1383,1409,1315,1304,1362,1378,1380,1404,1421,1421
LA,1354,1354,1354,1354,1354,1354,1354,1354,1354,1354,...,1280,1310,1235,1240,1298,1313,1296,1323,1354,1354
KS,1310,1310,1310,1310,1310,1310,1310,1310,1310,1310,...,1253,1282,1169,1176,1229,1310,1310,1310,1310,1310
IA,1309,1309,1309,1309,1309,1309,1309,1309,1309,1309,...,1250,1285,1184,1149,1242,1309,1309,1309,1309,1309
SC,1280,1280,1280,1280,1280,1280,1280,1280,1280,1280,...,1266,1266,1266,1266,1266,1266,1266,1266,1280,1280
OR,1263,1263,1263,1263,1263,1263,1263,1263,1263,1263,...,1263,1263,1263,1263,1263,1263,1263,1263,1263,1263
UT,1113,1113,1113,1113,1113,1113,1113,1113,1113,1113,...,1023,1034,948,939,975,1043,1040,1045,1113,1113
NE,1086,1086,1086,1086,1086,1086,1086,1086,1086,1086,...,1009,1009,1009,1009,1009,1009,1009,1009,1086,1086
AR,1080,1080,1080,1080,1080,1080,1080,1080,1080,1080,...,1042,1061,927,912,981,1066,1057,1068,1080,1080
MS,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,...,905,960,932,929,976,1001,1003,1019,1042,1042
CT,1001,1001,1001,1001,1001,1001,1001,1001,1001,1001,...,998,1000,977,964,992,998,998,1001,1001,1001
NM,886,886,886,886,886,886,886,886,886,886,...,873,879,573,565,645,844,835,856,886,886
PR,849,849,849,849,849,849,849,849,849,849,...,841,841,0,0,0,147,132,227,849,849
MT,829,829,829,829,829,829,829,829,829,829,...,826,826,826,826,826,826,826,826,829,829
ID,791,791,791,791,791,791,791,791,791,791,...,772,772,772,772,772,772,772,772,791,791
NV,754,754,754,754,754,754,754,754,754,753,...,720,720,720,720,720,720,720,720,754,754
SD,722,722,722,722,722,722,722,722,722,722,...,706,706,706,706,706,706,706,706,722,722
WV,711,711,711,711,711,711,711,711,711,711,...,411,496,539,527,594,672,663,672,711,711
ME,602,602,602,602,602,602,602,602,602,602,...,436,500,442,447,492,568,568,568,602,602
ND,531,531,531,531,531,531,531,531,531,531,...,394,426,342,349,394,474,472,476,531,531
AK,509,509,509,509,509,509,509,509,509,509,...,503,503,503,503,503,503,503,503,509,509
NH,496,496,496,496,496,496,496,496,496,496,...,416,447,403,406,436,496,496,496,496,496
WY,364,364,364,364,364,364,364,364,364,364,...,364,364,364,364,364,364,364,364,364,364
RI,314,314,314,314,314,314,314,314,314,314,...,301,305,298,292,304,305,305,306,314,314
VT,305,305,305,305,305,305,305,305,305,305,...,248,278,223,227,247,305,305,305,305,305
HI,295,295,295,295,295,295,295,295,295,295,...,293,294,294,294,294,286,279,287,295,295
DC,235,235,235,235,235,235,235,235,235,235,...,216,228,152,151,171,146,138,160,235,235
DE,230,230,230,230,230,230,230,230,230,228,...,221,225,217,215,220,225,224,225,230,230
BI,174,174,174,174,174,174,174,174,174,174,...,4,4,4,4,4,4,4,4,174,174
GU,44,44,44,44,44,44,44,44,44,44,...,41,41,41,41,41,41,41,41,44,44
MP,35,35,35,35,35,35,35,35,35,35,...,0,0,0,0,0,0,0,0,35,35
AS,29,29,29,29,29,29,29,29,29,29,...,1,3,0,0,0,3,5,6,29,29
VI,23,23,23,23,23,23,23,23,23,23,...,22,22,10,11,14,18,19,21,23,23

In [129]:
percent_elem=(round(elem_schools.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME/(pubschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME)*100, 3).reset_index())

In [130]:
percent_elem=percent_elem.rename(columns={'STABR':'State', 'SCH_NAME':'Percent_elem'})

In [131]:
percent_elem

   State  Percent_elem
0     AK        33.792
1     AL        45.093
2     AR        47.685
3     AS        79.310
4     AZ        48.669
5     BI        62.069
6     CA        57.783
7     CO        54.229
8     CT        60.340
9     DC        60.851
10    DE        51.739
11    FL        52.144
12    GA        56.772
13    GU        61.364
14    HI        62.373
15    IA        52.101
16    ID        49.052
17    IL        53.490
18    IN        55.521
19    KS        55.267
20    KY        47.258
21    LA        53.250
22    MA        57.073
23    MD        62.562
24    ME        58.638
25    MI        46.665
26    MN        38.749
27    MO        49.715
28    MP        25.714
29    MS        42.418
30    MT        51.628
31    NC        54.396
32    ND        51.224
33    NE        49.816
34    NH        57.460
35    NJ        58.418
36    NM        51.580
37    NV        56.499
38    NY        53.053
39    OH        50.340
40    OK        52.179
41    OR        56.453
42    PA        55.556
43    PR        60.895
44    RI        55.732
45    SC        54.062
46    SD        45.429
47    TN        54.468
48    TX        49.741
49    UT        56.244
50    VA        53.850
51    VI        65.217
52    VT        68.197
53    WA        48.664
54    WI        50.000
55    WV        57.806
56    WY        53.297

In [69]:
elem_schools=pubschool.loc[pubschool['SCHOOL_LEVEL']=='Elementary']

In [73]:
highschool=pubschool.loc[pubschool['SCHOOL_LEVEL']=='High']

In [74]:
highschool

,X,Y,OBJECTID,NCESSCH,SURVYEAR,STABR,LEAID,ST_LEAID,LEA_NAME,SCH_NAME,...,HIALF,HI,TRALM,TRALF,TR,WHALM,WHALF,WH,LATCOD,LONCOD
1,-86.204900,34.262200,2,10000500871,2020-2021,AL,100005,AL-101,Albertville City,Albertville High School,...,371.0,785.0,17.0,21.0,38.0,368.0,338.0,706.0,34.262200,-86.204900
7,-86.142000,34.362500,8,10000600872,2020-2021,AL,100006,AL-048,Marshall County,Asbury High School,...,160.0,285.0,1.0,2.0,3.0,182.0,146.0,328.0,34.362500,-86.142000
10,-86.319462,34.178658,11,10000600878,2020-2021,AL,100006,AL-048,Marshall County,Douglas High School,...,119.0,255.0,2.0,3.0,5.0,203.0,177.0,380.0,34.178658,-86.319462
12,-86.253261,34.534948,13,10000600883,2020-2021,AL,100006,AL-048,Marshall County,Kate D Smith DAR High School,...,5.0,14.0,6.0,1.0,7.0,225.0,180.0,405.0,34.534948,-86.253261
15,-86.285900,34.305400,16,10000600987,2020-2021,AL,100006,AL-048,Marshall County,Marshall Technical School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.305400,-86.285900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100698,-66.399500,18.431900,100699,720003002085,2020-2021,PR,7200030,PR-01,PUERTO RICO DEPARTMENT OF EDUCATION,JUAN QUIRINDONGO MORELL (SUPERIOR),...,256.0,499.0,NaN,NaN,NaN,NaN,NaN,NaN,18.431900,-66.399500
100704,-64.798638,17.722947,100705,780000200013,2020-2021,VI,7800002,VI-002,Saint Croix School District,ST. CROIX EDUCATIONAL COMPEX HIGH SCHOOL,...,97.0,183.0,NaN,1.0,1.0,4.0,2.0,6.0,17.722947,-64.798638
100709,-64.780456,17.725655,100710,780000200030,2020-2021,VI,7800002,VI-002,Saint Croix School District,SAINT CROIX CENTRAL HIGH,...,142.0,277.0,1.0,4.0,5.0,4.0,NaN,4.0,17.725655,-64.780456
100711,-64.918749,18.342037,100712,780003000005,2020-2021,VI,7800030,VI-001,Saint Thomas - Saint John School District,CHARLOTTE AMALIE HIGH SCHOOL,...,88.0,170.0,1.0,6.0,7.0,11.0,10.0,21.0,18.342037,-64.918749
100712,-64.853909,18.324876,100713,780003000015,2020-2021,VI,7800030,VI-001,Saint Thomas - Saint John School District,IVANNA EUDORA KEAN HIGH SCHOOL,...,21.0,57.0,1.0,3.0,4.0,2.0,1.0,3.0,18.324876,-64.853909

In [132]:
percent_high=(round(highschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME/(pubschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME)*100, 3).reset_index())

In [133]:
percent_high=percent_high.rename(columns={'STABR':'State', 'SCH_NAME':'Percent_High'})

In [134]:
percent_high

   State  Percent_High
0     AK        15.324
1     AL        26.235
2     AR        27.870
3     AS        20.690
4     AZ        30.323
5     BI        12.644
6     CA        21.607
7     CO        22.574
8     CT        19.680
9     DC        17.021
10    DE        18.261
11    FL        22.170
12    GA        19.602
13    GU        15.909
14    HI        14.576
15    IA        25.745
16    ID        25.917
17    IL        21.852
18    IN        21.504
19    KS        26.183
20    KY        28.851
21    LA        20.384
22    MA        20.108
23    MD        16.890
24    ME        19.601
25    MI        28.202
26    MN        36.310
27    MO        26.992
28    MP        17.143
29    MS        30.326
30    MT        20.869
31    NC        21.575
32    ND        31.073
33    NE        24.770
34    NH        19.153
35    NJ        18.862
36    NM        24.718
37    NV        19.629
38    NY        24.488
39    OH        25.510
40    OK        26.089
41    OR        21.219
42    PA        24.289
43    PR        23.086
44    RI        20.701
45    SC        22.656
46    SD        27.008
47    TN        21.489
48    TX        19.436
49    UT        17.610
50    VA        15.258
51    VI        17.391
52    VT        20.656
53    WA        26.047
54    WI        24.889
55    WV        22.644
56    WY        24.725

In [91]:
highschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False)

,X,Y,OBJECTID,NCESSCH,SURVYEAR,LEAID,ST_LEAID,LEA_NAME,SCH_NAME,LSTREET1,...,HIALF,HI,TRALM,TRALF,TR,WHALM,WHALF,WH,LATCOD,LONCOD
STABR,,,,,,,,,,,,,,,,,,,,,
CA,2232,2232,2232,2232,2232,2232,2232,2232,2232,2232,...,2220,2225,2043,2042,2122,2163,2150,2189,2232,2232
TX,1840,1840,1840,1840,1840,1840,1840,1840,1840,1840,...,1840,1840,1840,1840,1840,1840,1840,1840,1840,1840
NY,1183,1183,1183,1183,1183,1183,1183,1183,1183,1183,...,1148,1172,979,967,1067,1139,1111,1166,1183,1183
MI,1002,1002,1002,1002,1002,1002,1002,1002,1002,1002,...,1002,1002,1002,1002,1002,1002,1002,1002,1002,1002
IL,958,958,958,958,958,958,958,958,958,958,...,646,677,602,584,638,666,667,678,958,958
FL,946,946,946,946,946,946,946,946,946,946,...,944,944,944,944,944,944,944,944,946,946
MN,923,923,923,923,923,923,923,923,923,923,...,864,891,843,829,867,908,909,916,923,923
OH,901,901,901,901,901,901,901,901,901,901,...,901,901,901,901,901,901,901,901,901,901
AZ,752,752,752,752,752,752,752,752,752,752,...,752,752,752,752,752,752,752,752,752,752
PA,717,717,717,717,717,717,717,717,717,717,...,716,716,716,716,716,716,716,716,717,717
MO,664,664,664,664,664,664,664,664,664,664,...,547,598,520,513,554,662,661,664,664,664
WA,653,653,653,653,653,653,653,653,653,653,...,635,643,610,615,628,650,648,651,653,653
NC,589,589,589,589,589,589,589,589,589,589,...,587,587,587,587,587,587,587,587,589,589
WI,562,562,562,562,562,562,562,562,562,562,...,524,545,491,494,530,553,551,555,562,562
NJ,484,484,484,484,484,484,484,484,484,484,...,475,480,378,377,399,463,463,475,484,484
OK,467,467,467,467,467,467,467,467,467,467,...,419,453,467,465,467,467,464,467,467,467
GA,453,453,453,453,453,453,453,453,453,453,...,452,452,452,452,452,452,452,452,453,453
KY,442,442,442,442,442,442,442,442,442,442,...,429,435,424,424,435,439,439,442,442,442
CO,435,435,435,435,435,435,435,435,435,435,...,426,427,367,369,394,426,427,428,435,435
IN,409,409,409,409,409,409,409,409,409,409,...,399,407,397,396,406,407,406,409,409,409
AL,409,409,409,409,409,409,409,409,409,409,...,301,301,301,301,301,301,301,301,409,409
TN,404,404,404,404,404,404,404,404,404,404,...,382,390,353,351,370,395,392,400,404,404
MA,371,371,371,371,371,371,371,371,371,371,...,366,369,349,344,360,369,366,370,371,371
KS,343,343,343,343,343,343,343,343,343,343,...,324,339,290,292,313,343,343,343,343,343
IA,337,337,337,337,337,337,337,337,337,337,...,322,333,307,292,325,337,337,337,337,337
VA,325,325,325,325,325,325,325,325,325,325,...,325,325,325,325,325,325,325,325,325,325
MS,316,316,316,316,316,316,316,316,316,316,...,288,297,278,289,298,311,312,314,316,316
AR,301,301,301,301,301,301,301,301,301,301,...,292,298,253,249,272,301,296,301,301,301
SC,290,290,290,290,290,290,290,290,290,290,...,290,290,290,290,290,290,290,290,290,290
LA,276,276,276,276,276,276,276,276,276,276,...,261,266,251,256,269,271,265,272,276,276
NE,269,269,269,269,269,269,269,269,269,269,...,269,269,269,269,269,269,269,269,269,269
OR,268,268,268,268,268,268,268,268,268,268,...,268,268,268,268,268,268,268,268,268,268
MD,240,240,240,240,240,240,240,240,240,240,...,227,235,212,208,222,230,232,237,240,240
NM,219,219,219,219,219,219,219,219,219,219,...,216,219,132,129,147,210,209,213,219,219
ID,205,205,205,205,205,205,205,205,205,205,...,205,205,205,205,205,205,205,205,205,205
CT,197,197,197,197,197,197,197,197,197,197,...,196,196,190,190,196,196,195,197,197,197
UT,196,196,196,196,196,196,196,196,196,196,...,173,177,155,148,159,176,175,177,196,196
PR,196,196,196,196,196,196,196,196,196,196,...,196,196,0,0,0,37,34,61,196,196
SD,195,195,195,195,195,195,195,195,195,195,...,195,195,195,195,195,195,195,195,195,195
MT,173,173,173,173,173,173,173,173,173,173,...,173,173,173,173,173,173,173,173,173,173
ND,165,165,165,165,165,165,165,165,165,165,...,113,131,93,94,115,161,159,161,165,165
WV,161,161,161,161,161,161,161,161,161,161,...,88,103,103,97,109,129,123,129,161,161
NV,148,148,148,148,148,148,148,148,148,148,...,147,147,147,147,147,147,147,147,148,148
ME,118,118,118,118,118,118,118,118,118,118,...,100,109,97,94,103,118,118,118,118,118
NH,95,95,95,95,95,95,95,95,95,95,...,84,89,82,83,87,95,95,95,95,95
WY,90,90,90,90,90,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
AK,78,78,78,78,78,78,78,78,78,78,...,78,78,78,78,78,78,78,78,78,78
RI,65,65,65,65,65,65,65,65,65,65,...,58,59,56,56,58,58,58,59,65,65
VT,63,63,63,63,63,63,63,63,63,63,...,59,60,53,55,56,63,63,63,63,63
HI,43,43,43,43,43,43,43,43,43,43,...,43,43,43,43,43,43,43,43,43,43
DE,42,42,42,42,42,42,42,42,42,41,...,41,42,40,40,40,42,42,42,42,42
DC,40,40,40,40,40,40,40,40,40,40,...,36,39,27,24,29,22,19,23,40,40
BI,22,22,22,22,22,22,22,22,22,22,...,1,1,1,1,1,1,1,1,22,22
GU,7,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
AS,6,6,6,6,6,6,6,6,6,6,...,0,1,0,0,0,0,2,2,6,6
MP,6,6,6,6,6,6,6,6,6,6,...,0,0,0,0,0,0,0,0,6,6
VI,4,4,4,4,4,4,4,4,4,4,...,4,4,3,4,4,4,3,4,4,4

In [75]:
midschool=pubschool.loc[pubschool['SCHOOL_LEVEL']=='Middle']

In [87]:
midschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False)

,X,Y,OBJECTID,NCESSCH,SURVYEAR,LEAID,ST_LEAID,LEA_NAME,SCH_NAME,LSTREET1,...,HIALF,HI,TRALM,TRALF,TR,WHALM,WHALF,WH,LATCOD,LONCOD
STABR,,,,,,,,,,,,,,,,,,,,,
TX,1753,1753,1753,1753,1753,1753,1753,1753,1753,1753,...,1753,1753,1753,1753,1753,1753,1753,1753,1753,1753
CA,1410,1410,1410,1410,1410,1410,1410,1410,1410,1410,...,1406,1407,1284,1291,1335,1349,1350,1378,1410,1410
NY,809,809,809,809,809,809,809,809,809,809,...,797,803,672,670,719,789,781,802,809,809
IL,720,720,720,720,720,720,720,720,720,720,...,653,672,645,639,669,689,686,694,720,720
OH,659,659,659,659,659,659,659,659,659,659,...,659,659,659,659,659,659,659,659,659,659
FL,588,588,588,588,588,588,588,588,588,588,...,588,588,588,588,588,588,588,588,588,588
PA,524,524,524,524,524,524,524,524,524,524,...,524,524,524,524,524,524,524,524,524,524
MI,508,508,508,508,508,508,508,508,508,508,...,508,508,508,508,508,508,508,508,508,508
NC,486,486,486,486,486,486,486,486,486,486,...,486,486,486,486,486,486,486,486,486,486
GA,477,477,477,477,477,477,477,477,477,477,...,477,477,477,477,477,477,477,477,477,477
NJ,430,430,430,430,430,430,430,430,430,430,...,427,429,380,386,403,424,422,424,430,430
WI,403,403,403,403,403,403,403,403,403,403,...,376,391,361,363,385,400,400,401,403,403
MO,397,397,397,397,397,397,397,397,397,397,...,359,378,350,355,369,387,389,390,397,397
WA,378,378,378,378,378,378,378,378,378,378,...,374,375,364,368,373,378,377,378,378,378
OK,365,365,365,365,365,365,365,365,365,365,...,354,361,365,365,365,365,364,365,365,365
TN,357,357,357,357,357,357,357,357,357,357,...,350,354,339,337,347,345,341,352,357,357
VA,347,347,347,347,347,347,347,347,347,347,...,347,347,347,347,347,347,347,347,347,347
IN,331,331,331,331,331,331,331,331,331,331,...,325,330,326,325,329,330,329,330,331,331
MA,323,323,323,323,323,323,323,323,323,323,...,320,322,312,305,318,321,320,322,323,323
MN,321,321,321,321,321,321,321,321,321,321,...,299,311,295,300,307,309,303,311,321,321
CO,288,288,288,288,288,288,288,288,288,288,...,287,287,262,264,272,287,286,288,288,288
AL,257,257,257,257,257,257,257,257,257,257,...,256,256,256,256,256,256,256,256,257,257
SC,251,251,251,251,251,251,251,251,251,251,...,251,251,251,251,251,251,251,251,251,251
IA,250,250,250,250,250,250,250,250,250,250,...,240,245,224,219,237,250,250,250,250,250
AZ,232,232,232,232,232,232,232,232,232,232,...,232,232,232,232,232,232,232,232,232,232
MD,229,229,229,229,229,229,229,229,229,229,...,224,228,220,219,224,223,226,226,229,229
LA,226,226,226,226,226,226,226,226,226,226,...,213,219,207,206,218,221,221,223,226,226
MT,225,225,225,225,225,225,225,225,225,225,...,225,225,225,225,225,225,225,225,225,225
KS,224,224,224,224,224,224,224,224,224,224,...,217,220,197,199,208,224,224,224,224,224
KY,220,220,220,220,220,220,220,220,220,220,...,213,220,211,212,218,218,218,220,220,220
AR,209,209,209,209,209,209,209,209,209,209,...,206,208,187,187,195,207,207,207,209,209
OR,204,204,204,204,204,204,204,204,204,204,...,204,204,204,204,204,204,204,204,204,204
MS,186,186,186,186,186,186,186,186,186,186,...,162,172,162,160,170,175,178,181,186,186
CT,179,179,179,179,179,179,179,179,179,179,...,179,179,175,173,177,179,179,179,179,179
SD,169,169,169,169,169,169,169,169,169,169,...,169,169,169,169,169,169,169,169,169,169
NM,164,164,164,164,164,164,164,164,164,164,...,159,161,95,91,109,154,151,157,164,164
UT,141,141,141,141,141,141,141,141,141,141,...,137,137,128,129,129,137,137,137,141,141
NE,128,128,128,128,128,128,128,128,128,128,...,128,128,128,128,128,128,128,128,128,128
NV,117,117,117,117,117,117,117,117,117,117,...,117,117,117,117,117,117,117,117,117,117
ID,114,114,114,114,114,114,114,114,114,114,...,113,113,113,113,113,113,113,113,114,114
WV,111,111,111,111,111,111,111,111,111,111,...,87,99,100,99,107,111,111,111,111,111
NH,100,100,100,100,100,100,100,100,100,100,...,92,98,87,89,95,100,100,100,100,100
PR,94,94,94,94,94,94,94,94,94,94,...,94,94,0,0,0,14,11,21,94,94
ME,85,85,85,85,85,85,85,85,85,85,...,74,81,75,78,81,85,85,85,85,85
WY,61,61,61,61,61,61,61,61,61,61,...,61,61,61,61,61,61,61,61,61,61
RI,59,59,59,59,59,59,59,59,59,59,...,58,59,59,58,59,59,59,59,59,59
ND,42,42,42,42,42,42,42,42,42,42,...,38,41,37,38,40,40,40,40,42,42
HI,42,42,42,42,42,42,42,42,42,42,...,42,42,42,42,42,42,40,42,42,42
DC,41,41,41,41,41,41,41,41,41,41,...,39,40,20,19,22,18,16,21,41,41
AK,38,38,38,38,38,38,38,38,38,38,...,38,38,38,38,38,38,38,38,38,38
DE,37,37,37,37,37,37,37,37,37,37,...,36,37,37,36,37,37,37,37,37,37
VT,26,26,26,26,26,26,26,26,26,26,...,20,24,19,20,22,26,26,26,26,26
GU,9,9,9,9,9,9,9,9,9,9,...,8,8,8,8,8,8,8,8,9,9
MP,5,5,5,5,5,5,5,5,5,5,...,0,0,0,0,0,0,0,0,5,5
BI,5,5,5,5,5,5,5,5,5,5,...,0,0,0,0,0,0,0,0,5,5
VI,3,3,3,3,3,3,3,3,3,3,...,3,3,2,0,2,3,3,3,3,3

In [135]:
percent_mid=(round(midschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME/(pubschool.groupby('STABR').count().sort_values('SCH_NAME', ascending=False).SCH_NAME)*100, 3).reset_index())

In [136]:
percent_mid=percent_mid.rename(columns={'STABR':'State', 'SCH_NAME':'Percent_mid'})

In [137]:
percent_mid

   State  Percent_mid
0     AK        7.466
1     AL       16.485
2     AR       19.352
3     AS          NaN
4     AZ        9.355
5     BI        2.874
6     CA       13.650
7     CO       14.946
8     CT       17.882
9     DC       17.447
10    DE       16.087
11    FL       13.780
12    GA       20.640
13    GU       20.455
14    HI       14.237
15    IA       19.099
16    ID       14.412
17    IL       16.423
18    IN       17.403
19    KS       17.099
20    KY       14.360
21    LA       16.691
22    MA       17.507
23    MD       16.115
24    ME       14.120
25    MI       14.298
26    MN       12.628
27    MO       16.138
28    MP       14.286
29    MS       17.850
30    MT       27.141
31    NC       17.802
32    ND        7.910
33    NE       11.786
34    NH       20.161
35    NJ       16.758
36    NM       18.510
37    NV       15.517
38    NY       16.746
39    OH       18.658
40    OK       20.391
41    OR       16.152
42    PA       17.751
43    PR       11.072
44    RI       18.790
45    SC       19.609
46    SD       23.407
47    TN       18.989
48    TX       18.517
49    UT       12.668
50    VA       16.291
51    VI       13.043
52    VT        8.525
53    WA       15.078
54    WI       17.848
55    WV       15.612
56    WY       16.758

In [138]:
school_perc=percent_elem.merge(percent_high, how='outer', on='State')

In [140]:
school_perc=school_perc.merge(percent_mid, how='outer', on='State')

In [144]:
school_perc['Percent_unaccounted']=(100-(school_perc.Percent_elem+school_perc.Percent_High+school_perc.Percent_mid))

In [145]:
school_perc

   State  Percent_elem  Percent_High  Percent_mid  Percent_unaccounted
0     AK        33.792        15.324        7.466               43.418
1     AL        45.093        26.235       16.485               12.187
2     AR        47.685        27.870       19.352                5.093
3     AS        79.310        20.690          NaN                  NaN
4     AZ        48.669        30.323        9.355               11.653
5     BI        62.069        12.644        2.874               22.413
6     CA        57.783        21.607       13.650                6.960
7     CO        54.229        22.574       14.946                8.251
8     CT        60.340        19.680       17.882                2.098
9     DC        60.851        17.021       17.447                4.681
10    DE        51.739        18.261       16.087               13.913
11    FL        52.144        22.170       13.780               11.906
12    GA        56.772        19.602       20.640                2.986
13    GU        61.364        15.909       20.455                2.272
14    HI        62.373        14.576       14.237                8.814
15    IA        52.101        25.745       19.099                3.055
16    ID        49.052        25.917       14.412               10.619
17    IL        53.490        21.852       16.423                8.235
18    IN        55.521        21.504       17.403                5.572
19    KS        55.267        26.183       17.099                1.451
20    KY        47.258        28.851       14.360                9.531
21    LA        53.250        20.384       16.691                9.675
22    MA        57.073        20.108       17.507                5.312
23    MD        62.562        16.890       16.115                4.433
24    ME        58.638        19.601       14.120                7.641
25    MI        46.665        28.202       14.298               10.835
26    MN        38.749        36.310       12.628               12.313
27    MO        49.715        26.992       16.138                7.155
28    MP        25.714        17.143       14.286               42.857
29    MS        42.418        30.326       17.850                9.406
30    MT        51.628        20.869       27.141                0.362
31    NC        54.396        21.575       17.802                6.227
32    ND        51.224        31.073        7.910                9.793
33    NE        49.816        24.770       11.786               13.628
34    NH        57.460        19.153       20.161                3.226
35    NJ        58.418        18.862       16.758                5.962
36    NM        51.580        24.718       18.510                5.192
37    NV        56.499        19.629       15.517                8.355
38    NY        53.053        24.488       16.746                5.713
39    OH        50.340        25.510       18.658                5.492
40    OK        52.179        26.089       20.391                1.341
41    OR        56.453        21.219       16.152                6.176
42    PA        55.556        24.289       17.751                2.404
43    PR        60.895        23.086       11.072                4.947
44    RI        55.732        20.701       18.790                4.777
45    SC        54.062        22.656       19.609                3.673
46    SD        45.429        27.008       23.407                4.156
47    TN        54.468        21.489       18.989                5.054
48    TX        49.741        19.436       18.517               12.306
49    UT        56.244        17.610       12.668               13.478
50    VA        53.850        15.258       16.291               14.601
51    VI        65.217        17.391       13.043                4.349
52    VT        68.197        20.656        8.525                2.622
53    WA        48.664        26.047       15.078               10.211
54    WI        50.000        24.889       17.848                7.263
55    WV        57.806        22.644       15.612                3.938
56    WY        53.297        24.725       16.758                5.220